services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  web:
    build: .
    tty: true
    stdin_open: true
    environment:
      DB_HOST: db
      DB_NAME: loan_profit_calculator_development
      DB_USERNAME: postgres
      DB_PASSWORD: password
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  db_data: {}
  redis_data: {}
